'use strict'

const {
	default: makeWASocket,
	useMultiFileAuthState,
	DisconnectReason
} = require('@whiskeysockets/baileys')
const pino = require('pino')

const PHONE_NUMBER = process.env.WHATSAPP_PHONE_NUMBER
const AUTH_DIR = process.env.AUTH_DIR || 'session'
const STATUS_JID = 'status@broadcast'

// Bounded in-memory dedupe set so the same status is never processed twice.
// No database, no disk writes: this is intentionally volatile.
const MAX_SEEN = 2000
const seenStatusIds = new Set()

function markSeen(id) {
	if (seenStatusIds.has(id)) return false
	seenStatusIds.add(id)
	if (seenStatusIds.size > MAX_SEEN) {
		// Drop the oldest half. Sets preserve insertion order in JS.
		const it = seenStatusIds.values()
		for (let i = 0; i < MAX_SEEN / 2; i++) {
			seenStatusIds.delete(it.next().value)
		}
	}
	return true
}

// Silence the library's own logger; we emit our own minimal log lines below.
const logger = pino({ level: 'silent' })

let reconnectAttempt = 0
const MAX_BACKOFF_MS = 30000

function backoffDelay() {
	const delay = Math.min(MAX_BACKOFF_MS, 1000 * 2 ** Math.min(reconnectAttempt, 5))
	reconnectAttempt += 1
	return delay
}

async function start() {
	if (!PHONE_NUMBER) {
		console.error('Fatal error: WHATSAPP_PHONE_NUMBER environment variable is not set')
		process.exit(1)
	}

	const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR)

	const sock = makeWASocket({
		auth: state,
		logger,
		printQRInTerminal: false,
		syncFullHistory: false,
		markOnlineOnConnect: false
	})

	sock.ev.on('creds.update', saveCreds)

	sock.ev.on('connection.update', async (update) => {
		const { connection, lastDisconnect, qr } = update

		if (connection === 'connecting' && !sock.authState.creds.registered && !qr) {
			try {
				console.log('Pairing required')
				// The pairing code below is generated by WhatsApp itself via the
				// library's own auth mechanism. It is never invented, and it is
				// only ever printed here — never written to disk or logged again.
				await new Promise((resolve) => setTimeout(resolve, 3000))
				const code = await sock.requestPairingCode(PHONE_NUMBER)
				console.log(`Enter this pairing code on your phone: ${code}`)
			} catch (err) {
				console.error('Fatal error: could not request pairing code:', err.message)
			}
		}

		if (connection === 'open') {
			reconnectAttempt = 0
			console.log('Connected')
		}

		if (connection === 'close') {
			const statusCode = lastDisconnect?.error?.output?.statusCode
			const loggedOut = statusCode === DisconnectReason.loggedOut

			console.log('Disconnected')

			if (loggedOut) {
				console.error('Fatal error: session logged out, re-pairing will be required')
				process.exit(1)
			}

			console.log('Reconnecting')
			setTimeout(() => {
				start().catch((err) => {
					console.error('Fatal error:', err.message)
					process.exit(1)
				})
			}, backoffDelay())
		}
	})

	sock.ev.on('messages.upsert', async ({ messages }) => {
		for (const msg of messages) {
			const key = msg.key
			if (!key || key.remoteJid !== STATUS_JID || key.fromMe) continue
			if (!key.id || !markSeen(key.id)) continue

			try {
				await sock.readMessages([key])
				console.log('Status viewed')
			} catch (err) {
				console.error('Fatal error: could not mark status as viewed:', err.message)
			}
		}
	})
}

function shutdown() {
	process.exit(0)
}

process.on('SIGTERM', shutdown)
process.on('SIGINT', shutdown)

process.on('uncaughtException', (err) => {
	console.error('Fatal error:', err.message)
	process.exit(1)
})

process.on('unhandledRejection', (err) => {
	console.error('Fatal error:', err && err.message ? err.message : err)
	process.exit(1)
})

console.log('CHELYN starting')
start().catch((err) => {
	console.error('Fatal error:', err.message)
	process.exit(1)
})
